/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_bibliotheque;

import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Ajout_etud extends javax.swing.JFrame {

    /**
     * Creates new form Ajout_etud
     */
    public Ajout_etud() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        nom = new javax.swing.JLabel();
        prenom = new javax.swing.JLabel();
        lab_nom = new javax.swing.JTextField();
        matricule = new javax.swing.JLabel();
        lab_prenom = new javax.swing.JTextField();
        universite = new javax.swing.JLabel();
        lab_matricule = new javax.swing.JTextField();
        telephone = new javax.swing.JLabel();
        lab_universite = new javax.swing.JTextField();
        lab_telephone = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        lab_password = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        type = new javax.swing.JLabel();
        lab_type = new javax.swing.JComboBox();
        lab_nom1 = new javax.swing.JLabel();
        lab_prenom1 = new javax.swing.JLabel();
        lab_matricule1 = new javax.swing.JLabel();
        lab_universite1 = new javax.swing.JLabel();
        lab_telephone1 = new javax.swing.JLabel();
        lab_password1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel10.setText("AJOUT D'UN ADHERANT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(jLabel10)
                .addContainerGap(448, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        nom.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nom.setForeground(new java.awt.Color(255, 255, 255));
        nom.setText("MATRICULE          :");

        prenom.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        prenom.setForeground(new java.awt.Color(255, 255, 255));
        prenom.setText("NOM     :");

        lab_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lab_nomActionPerformed(evt);
            }
        });

        matricule.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        matricule.setForeground(new java.awt.Color(255, 255, 255));
        matricule.setText("PRENOM     :");

        universite.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        universite.setForeground(new java.awt.Color(255, 255, 255));
        universite.setText("Universite    :");

        telephone.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        telephone.setForeground(new java.awt.Color(255, 255, 255));
        telephone.setText("Telephone    :");

        lab_universite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lab_universiteActionPerformed(evt);
            }
        });

        password.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password      :");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("AJOUTER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Prenom", "Matricule", "Universite", "Telephone", "password"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        type.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        type.setForeground(new java.awt.Color(255, 255, 255));
        type.setText("type     :");

        lab_type.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Etudiant_interne", "Etudiant_externe ", "Enseignant", "Administrateur", "Gestionnaire" }));

        lab_nom1.setForeground(new java.awt.Color(255, 0, 0));

        lab_prenom1.setForeground(new java.awt.Color(255, 0, 0));

        lab_matricule1.setForeground(new java.awt.Color(255, 0, 0));

        lab_universite1.setForeground(new java.awt.Color(255, 0, 0));

        lab_telephone1.setForeground(new java.awt.Color(255, 0, 0));

        lab_password1.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lab_type, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(universite, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telephone)
                                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(lab_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lab_telephone1)
                                            .addComponent(lab_password, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lab_password1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(matricule, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prenom))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lab_universite, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lab_prenom, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(lab_nom)
                                    .addComponent(lab_matricule)
                                    .addComponent(lab_nom1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lab_prenom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lab_matricule1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lab_universite1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(38, 38, 38)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lab_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(lab_nom1)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prenom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lab_prenom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(lab_prenom1)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(matricule, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lab_matricule, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(lab_matricule1)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(universite, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lab_universite, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lab_universite1)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lab_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(lab_telephone1)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lab_password, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lab_password1)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lab_type, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(551, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lab_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lab_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lab_nomActionPerformed

    private void lab_universiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lab_universiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lab_universiteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        lab_nom.setText("");
         lab_prenom.setText("");
          lab_matricule.setText("");
           lab_universite.setText("");
            lab_telephone.setText("");
             lab_password.setText("");
              lab_type.setSelectedItem("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
//         username.setText("");
//        password.setText("");
        // TODO add your handling code here:
                                          

                                           
        // TODO add your handling code here:
        if(lab_nom.getText().trim().isEmpty()){
           lab_nom1.setText("nom is Empty");
        } else if(lab_prenom.getText().trim().isEmpty()){
           lab_prenom1.setText("prenom is Empty");
        } else if(lab_matricule.getText().trim().isEmpty()){
           lab_matricule1.setText("matricule is Empty");
        }else if(lab_universite.getText().trim().isEmpty()){
           lab_universite1.setText("universite is Empty");
        }else if(lab_telephone.getText().trim().isEmpty()){
           lab_telephone1.setText("telephone is Empty");
        }else if(lab_password.getText().trim().isEmpty()){
           lab_password1.setText("password is Empty");
        }
//        else if(lab_type.getText().trim().isEmpty()){
//           lab_type1.setSelectedItem("type is Empty");
//        }
        
        else{ 
             String nom = lab_nom.getText();
              String prenom = lab_prenom.getText();
               String matricule = lab_matricule.getText();
                String universite = lab_universite.getText();
                String telephone = lab_telephone.getText();
                 String mdp = lab_password.getText();
                  String type = lab_type.getSelectedItem().toString();
        try {
                    
                        Class.forName("com.mysql.cj.jdbc.Driver");
                        System.out.println("3");
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
                        System.out.println("4");
                        
                       
                        System.out.println("5");
                       
                        System.out.println("6");
                        Statement stm = con.createStatement();
                        System.out.println("7");
                        String sql = "INSERT INTO abonne VALUES('"+matricule+"','"+nom+"','"+prenom+"','"+universite+"','"+telephone+"','"+mdp+"','"+type+"')";
                        System.out.println("8");
                          stm. executeUpdate(sql);
                         System.out.println("9");
                          JOptionPane.showMessageDialog(this,"adherant ajouter");
                          con.close();
                    } catch (Exception e) {
                       System.out.println(e.getMessage());
                    }
        }
        
//        if(lab_nom.getText().equals("")|| lab_prenom.getText().equals("")||lab_matricule.getText().equals("")||
//              lab_universite.getText().equals("")||lab_telephone.getText().equals("")||lab_password.getText().equals("")|| lab_type.getSelectedItem().equals("")){
//                 JOptionPane.showMessageDialog(this, "Please enter all data");
//        }else{
//            String data[] = {lab_nom.getText(),lab_prenom.getText(),lab_prenom.getText(),lab_matricule.getText(),lab_universite.getText(),lab_telephone.getText(),lab_password.getText(),lab_type.getSelectedItem().toString()};
//             DefaultTableModel tblmodel = (DefaultTableModel)jTable1.getModel();
//             tblmodel.addRow(data);
//              JOptionPane.showMessageDialog(this,"adherant ajouter");
//              lab_nom.setText("");
//         lab_prenom.setText("");
//          lab_matricule.setText("");
//           lab_universite.setText("");
//            lab_telephone.setText("");
//             lab_password.setText("");
//              lab_type.setSelectedItem("");
//             
//        }
        String sql = "SELECT * FROM abonne";
        try {
            PreparedStatement pst;
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
                        System.out.println("4");
                        
                       
                        System.out.println("5");
                       
                        System.out.println("6");
                        Statement stm = con.createStatement();
                        System.out.println("7");
                       pst = con.prepareStatement(sql);
                       ResultSet rs = pst.executeQuery();
//                       ResultSetMetaData rsm = rs.getMetaData();
                       java.sql.ResultSetMetaData rsm = rs.getMetaData();
                       int c = rsm.getColumnCount();
                       DefaultTableModel tblmodel = (DefaultTableModel)jTable1.getModel();
            tblmodel.setRowCount(c);
            while(rs.next()){
           Vector v2 = new Vector();
                for (int i = 0; i < c; i++) {
                   v2.add(rs.getString("nom"));
                   v2.add(rs.getString("prenom"));
                   v2.add(rs.getString("matricule"));
                   v2.add(rs.getString("universite"));
                   v2.add(rs.getString("telephone"));
                   v2.add(rs.getString("mdp"));
                   v2.add(rs.getString("type"));
                }
           tblmodel.addRow(v2);
           
        }
                       
                       
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this,"erreur"+e);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajout_etud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajout_etud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajout_etud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajout_etud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajout_etud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lab_matricule;
    private javax.swing.JLabel lab_matricule1;
    private javax.swing.JTextField lab_nom;
    private javax.swing.JLabel lab_nom1;
    private javax.swing.JTextField lab_password;
    private javax.swing.JLabel lab_password1;
    private javax.swing.JTextField lab_prenom;
    private javax.swing.JLabel lab_prenom1;
    private javax.swing.JTextField lab_telephone;
    private javax.swing.JLabel lab_telephone1;
    private javax.swing.JComboBox lab_type;
    private javax.swing.JTextField lab_universite;
    private javax.swing.JLabel lab_universite1;
    private javax.swing.JLabel matricule;
    private javax.swing.JLabel nom;
    private javax.swing.JLabel password;
    private javax.swing.JLabel prenom;
    private javax.swing.JLabel telephone;
    private javax.swing.JLabel type;
    private javax.swing.JLabel universite;
    // End of variables declaration//GEN-END:variables
}
